//aa file ma only context api no use karva react ne request kari chhe...

import { createContext } from "react";

const NoteContext = createContext();  //context banava mate...


export default NoteContext ; //biji file ma use kari shakay etale...