//aa file ma only context api no use karva react ne request kari chhe...

import { createContext } from "react";

const ContactContext = createContext();  //context banava mate...


export default ContactContext ; //biji file ma use kari shakay etale...